name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda_function/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10

      - name: Terraform Init and Apply
        env:
          TF_VAR_notion_token: ${{ secrets.NOTION_TOKEN }}
          TF_VAR_notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          TF_VAR_gmail_credentials: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
          TF_VAR_aws_region: eu-west-1
          TF_VAR_aws_profile: default
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
