name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    name: Plan Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda_function/requirements.txt

      - name: Setup AWS credentials from profile
        run: |
          mkdir -p ~/.aws
          echo "[sparkasse-notion-sync]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[sparkasse-notion-sync]" > ~/.aws/config
          echo "region=eu-west-1" >> ~/.aws/config

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10

      - name: Terraform Init
        env:
          TF_VAR_notion_token: ${{ secrets.NOTION_TOKEN }}
          TF_VAR_notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          TF_VAR_gmail_credentials: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
          TF_VAR_aws_region: eu-west-1
          TF_VAR_aws_profile: sparkasse-notion-sync
        run: terraform init

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_notion_token: ${{ secrets.NOTION_TOKEN }}
          TF_VAR_notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          TF_VAR_gmail_credentials: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
          TF_VAR_aws_region: eu-west-1
          TF_VAR_aws_profile: sparkasse-notion-sync
        run: terraform plan -out=tfplan

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  terraform_apply:
    name: Apply Terraform
    needs: terraform_plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS credentials from profile
        run: |
          mkdir -p ~/.aws
          echo "[sparkasse-notion-sync]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[sparkasse-notion-sync]" > ~/.aws/config
          echo "region=eu-west-1" >> ~/.aws/config

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Terraform Apply
        env:
          TF_VAR_notion_token: ${{ secrets.NOTION_TOKEN }}
          TF_VAR_notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          TF_VAR_gmail_credentials: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
          TF_VAR_aws_region: eu-west-1
          TF_VAR_aws_profile: sparkasse-notion-sync
        run: |
          terraform init
          terraform apply -auto-approve tfplan/tfplan
