name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda_function/requirements.txt

      - name: Install OpenTofu
        run: |
          curl -L https://github.com/opentofu/opentofu/releases/latest/download/opentofu_linux_amd64.tar.gz -o opentofu_linux_amd64.tar.gz
          tar -xzf opentofu_linux_amd64.tar.gz
          sudo mv opentofu /usr/local/bin/
          rm opentofu_linux_amd64.tar.gz

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: OpenTofu Init and Apply
        env:
          TF_VAR_notion_token: ${{ secrets.NOTION_TOKEN }}
          TF_VAR_notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          TF_VAR_gmail_credentials: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
        run: |
          opentofu init
          opentofu apply -auto-approve
